# Generated by Django 5.0 on 2023-12-17 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(max_length=100)),
                ('destino', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('cantidad_de_pasajeros_disponibles', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_de_pasajeros', models.IntegerField()),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boletos.viaje')),
            ],
        ),
    ]
