# Generated by Django 5.0 on 2023-12-17 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('inicio', models.DateTimeField()),
                ('fin', models.DateTimeField()),
            ],
        ),
    ]
